# Thu Mar 28 16:29:44 UTC 2024
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/a97083435/clash_233/config.yml"
    path: s.yml
    filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - {name: "@ Thu Mar 28 16:39:58 UTC 2024", type: load-balance, proxies: [E1,F1,E2,F2,E3,F3, ], url: &url "http://www.gstatic.com/generate_204", interval: &seconds 3000, strategy: &strategy round-robin}
  - {name: E0, type: select, proxies: &all [REJECT,DIRECT,MO_113.52.123.210_0328202435ad-413trojan,CLOUDFLARE_172.67.140.251_0328202435ad-650vmess,KR_152.70.248.80_0328202435ad-411trojan,PRIVATE_10.10.34.36_0328202435ad-595vmess,CN_157.254.231.141_032520245edd-43vmess,CN_103.184.44.190_0328202435ad-5401vmess,CN_36.134.16.190_03282024f5a8-109vmess,]}
  - {name: A0, type: select, use: [ps], proxies: [A2,A3,DIRECT,A3A2,E0,A2A3 ]}
  - {name: B0, type: select, use: [ps], proxies: [A2A3,DIRECT,A3,A2,E0,A3A2 ]}
  - {name: A2A3, type: relay, proxies: [A2,A3]}
  - {name: A3A2, type: relay, proxies: [A3,A2]}
  - {name: A3, type: fallback, proxies: [A4,A1], url: &baidu "http://www.baidu.com", interval: &delay 600}
  - {name: A4, type: load-balance, proxies: [A1,F1,F2,F3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A2, type: load-balance, proxies: [E1,E2,E3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A1, type: load-balance, use: [ps], url: *url, interval: *seconds, strategy: *strategy} 
  - {name: E1, type: url-test, proxies: [CN_157.254.231.141_032520245edd-43vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F1, type: load-balance, proxies: [MO_113.52.123.210_0328202435ad-413trojan,PRIVATE_10.10.34.36_0328202435ad-595vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E2, type: url-test, proxies: [CN_103.184.44.190_0328202435ad-5401vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F2, type: load-balance, proxies: [CLOUDFLARE_172.67.140.251_0328202435ad-650vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E3, type: url-test, proxies: [CN_36.134.16.190_03282024f5a8-109vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F3, type: load-balance, proxies: [KR_152.70.248.80_0328202435ad-411trojan,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
proxies:
  - {alterId: 0, cipher: auto, network: ws, port: 39025, server: 157.254.231.141, skip-cert-verify: false, tls: false, type: vmess, uuid: ca036aec-557f-47b0-94b0-4fe2bd31b687, ws-opts: {path: /ca036aec},"name":"CN_157.254.231.141_032520245edd-43vmess"}
  - {password: 82a6399e-0f33-4a7d-a2d9-cbbb48cb6bcd, port: 24852, server: kr01.freeflyingcloud.xyz, skip-cert-verify: false, type: trojan,"name":"KR_152.70.248.80_0328202435ad-411trojan"}
  - {password: 5eb5bdf9-4a70-4890-b2ca-8b2b79792639, port: 10443, server: macau.hapchung.com, skip-cert-verify: false, type: trojan,"name":"MO_113.52.123.210_0328202435ad-413trojan"}
  - {alterId: 0, cipher: auto, port: 11023, server: 36.134.16.190, skip-cert-verify: true, tls: false, type: vmess, uuid: 8c042a38-71c1-1dcb-00df-54880236e0dc,"name":"CN_36.134.16.190_03282024f5a8-109vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 2082, server: ying.appleid.bf, skip-cert-verify: false, tls: false, type: vmess, uuid: 97c752a2-43d3-4ac6-9369-b298b45feb3d, ws-opts: {path: '/ws?ed=2048'},"name":"CLOUDFLARE_172.67.140.251_0328202435ad-650vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 2086, server: index.zhaal.ir, skip-cert-verify: false, tls: false, type: vmess, uuid: e690ff9e-1676-4be3-d136-dcae586cb1e7, ws-opts: {path: /},"name":"PRIVATE_10.10.34.36_0328202435ad-595vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 103.184.44.190, skip-cert-verify: false, tls: true, type: vmess, uuid: dd41b5cb-b72e-4a8c-c75a-3ecc928d6eb3, ws-opts: {path: /blue},"name":"CN_103.184.44.190_0328202435ad-5401vmess"}
