# Fri Apr 28 16:22:34 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yml
    filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - {name: "@ Fri Apr 28 16:48:38 UTC 2023", type: load-balance, proxies: [E1,F1,E2,F2,E3,F3, ], url: &url "http://www.gstatic.com/generate_204", interval: &seconds 3000, strategy: &strategy round-robin}
  - {name: E0, type: select, proxies: &all [REJECT,DIRECT,HK_8.218.254.153_0428202334af-1084vmess,IN_152.70.74.66_0428202334af-778trojan,TW_1.171.228.38_0428202334af-1092vmess,DE_130.61.111.167_0428202334af-1177vmess,CN_36.134.16.96_0428202334af-989vmess,CN_112.132.215.189_0428202334af-943vmess,CN_120.232.233.149_0428202334af-1528vmess,CN_36.134.16.171_0428202334af-978vmess,CN_123.249.101.15_0428202334af-856vmess,]}
  - {name: A0, type: select, use: [ps], proxies: [A2,A3,DIRECT,A3A2,E0,A2A3 ]}
  - {name: B0, type: select, use: [ps], proxies: [A2A3,DIRECT,A3,A2,E0,A3A2 ]}
  - {name: A2A3, type: relay, proxies: [A2,A3]}
  - {name: A3A2, type: relay, proxies: [A3,A2]}
  - {name: A3, type: fallback, proxies: [A4,A1], url: &baidu "http://www.baidu.com", interval: &delay 600}
  - {name: A4, type: load-balance, proxies: [A1,F1,F2,F3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A2, type: load-balance, proxies: [E1,E2,E3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A1, type: load-balance, use: [ps], url: *url, interval: *seconds, strategy: *strategy} 
  - {name: E1, type: url-test, proxies: [CN_36.134.16.96_0428202334af-989vmess,CN_36.134.16.171_0428202334af-978vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F1, type: load-balance, proxies: [HK_8.218.254.153_0428202334af-1084vmess,DE_130.61.111.167_0428202334af-1177vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E2, type: url-test, proxies: [CN_112.132.215.189_0428202334af-943vmess,CN_123.249.101.15_0428202334af-856vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F2, type: load-balance, proxies: [IN_152.70.74.66_0428202334af-778trojan,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E3, type: url-test, proxies: [CN_120.232.233.149_0428202334af-1528vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F3, type: load-balance, proxies: [TW_1.171.228.38_0428202334af-1092vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
proxies:
  - {password: d906afe5-7c3c-4ddc-aaa4-61c154a82e5e, port: 443, server: 152.70.74.66, skip-cert-verify: true, type: trojan,"name":"IN_152.70.74.66_0428202334af-778trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 19709, server: 123.249.101.15, skip-cert-verify: false, tls: false, type: vmess, uuid: 2f278a45-940a-46c1-c886-77f3b2d33987, ws-opts: {path: /},"name":"CN_123.249.101.15_0428202334af-856vmess"}
  - {alterId: 64, cipher: auto, port: 50002, server: 112.132.215.189, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_112.132.215.189_0428202334af-943vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: n1680936927.lyqrdde.cn, skip-cert-verify: false, tls: true, type: vmess, uuid: 79c356e5-c00a-4843-90ec-846c43b795cf, ws-opts: {path: /},"name":"HK_8.218.254.153_0428202334af-1084vmess"}
  - {alterId: 0, cipher: auto, port: 11023, server: 36.134.16.171, skip-cert-verify: true, tls: false, type: vmess, uuid: 8c042a38-71c1-1dcb-00df-54880236e0dc,"name":"CN_36.134.16.171_0428202334af-978vmess"}
  - {alterId: 0, cipher: auto, port: 11023, server: 36.134.16.96, skip-cert-verify: true, type: vmess, uuid: 8c042a38-71c1-1dcb-00df-54880236e0dc,"name":"CN_36.134.16.96_0428202334af-989vmess"}
  - {alterId: 0, cipher: auto, port: 224, server: hinet1261.gfwisbest.xyz, skip-cert-verify: false, tls: false, type: vmess, uuid: 2285133e-b9ba-3fb5-a246-9c7ddcc2cd7a,"name":"TW_1.171.228.38_0428202334af-1092vmess"}
  - {alterId: 0, cipher: auto, port: 21872, server: 130.61.111.167, skip-cert-verify: true, tls: false, type: vmess, uuid: 9a7a75d4-ab7e-4ba0-bbfa-a4acddc18084,"name":"DE_130.61.111.167_0428202334af-1177vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 50030, server: bnm4.cdn.node.a.tddns-ounk.com, skip-cert-verify: false, tls: false, type: vmess, uuid: 9288e85f-9b18-3e89-bd66-221acdafbd1a, ws-opts: {path: /009c250b-54f5-43a8-8b18-dccbb5d8c66a.y.live01.m3u8},"name":"CN_120.232.233.149_0428202334af-1528vmess"}
