# Fri Apr  7 08:16:56 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yml
    filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - {name: "@ Fri Apr  7 08:36:21 UTC 2023", type: load-balance, proxies: [E1,F1,E2,F2,E3,F3, ], url: &url "http://www.gstatic.com/generate_204", interval: &seconds 3000, strategy: &strategy round-robin}
  - {name: E0, type: select, proxies: &all [REJECT,DIRECT,CLOUDFLARE_104.21.94.32_04072023a7d7-146vmess,IE_3.249.129.98_04072023a7d7-298trojan,US_140.99.94.41_04072023a7d7-217vmess,US_198.2.203.145_04072023a7d7-334vmess,KR_13.124.196.41_04062023989e-375trojan,CN_43.154.34.49_04062023989e-57vmess,CN_43.155.102.33_04072023a7d7-122vmess,CN_43.153.54.84_04072023a7d7-117vmess,CN_43.154.34.49_04062023989e-54vmess,CN_111.23.252.214_04072023a7d7-72vmess,CN_112.132.215.189_04072023359c-1105vmess,]}
  - {name: A0, type: select, use: [ps], proxies: [A2,A3,DIRECT,A3A2,E0,A2A3 ]}
  - {name: B0, type: select, use: [ps], proxies: [A2A3,DIRECT,A3,A2,E0,A3A2 ]}
  - {name: A2A3, type: relay, proxies: [A2,A3]}
  - {name: A3A2, type: relay, proxies: [A3,A2]}
  - {name: A3, type: fallback, proxies: [A4,A1], url: &baidu "http://www.baidu.com", interval: &delay 600}
  - {name: A4, type: load-balance, proxies: [A1,F1,F2,F3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A2, type: load-balance, proxies: [E1,E2,E3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A1, type: load-balance, use: [ps], url: *url, interval: *seconds, strategy: *strategy} 
  - {name: E1, type: url-test, proxies: [CN_43.154.34.49_04062023989e-57vmess,CN_43.154.34.49_04062023989e-54vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F1, type: load-balance, proxies: [CLOUDFLARE_104.21.94.32_04072023a7d7-146vmess,US_198.2.203.145_04072023a7d7-334vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E2, type: url-test, proxies: [CN_43.155.102.33_04072023a7d7-122vmess,CN_111.23.252.214_04072023a7d7-72vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F2, type: load-balance, proxies: [IE_3.249.129.98_04072023a7d7-298trojan,KR_13.124.196.41_04062023989e-375trojan,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E3, type: url-test, proxies: [CN_43.153.54.84_04072023a7d7-117vmess,CN_112.132.215.189_04072023359c-1105vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F3, type: load-balance, proxies: [US_140.99.94.41_04072023a7d7-217vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
proxies:
  - {alterId: 64, cipher: auto, network: tcp, port: 44108, server: 140.99.94.41, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"US_140.99.94.41_04072023a7d7-217vmess"}
  - {alterId: 0, cipher: auto, network: tcp, port: 23183, server: 43.154.34.49, skip-cert-verify: true, tls: false, type: vmess, uuid: b402a4af-285a-463e-c3a7-53f91efdec78,"name":"CN_43.154.34.49_04062023989e-54vmess"}
  - {alterId: 0, cipher: auto, port: 23183, server: 43.154.34.49, type: vmess, uuid: b402a4af-285a-463e-c3a7-53f91efdec78,"name":"CN_43.154.34.49_04062023989e-57vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: sg1.sharecentrepro.com, skip-cert-verify: true, tls: true, type: vmess, uuid: 823c31da-701f-483d-b36e-896e5cf0987a, ws-opts: {path: /shirker},"name":"CLOUDFLARE_104.21.94.32_04072023a7d7-146vmess"}
  - {alterId: 64, cipher: auto, port: 45070, server: 111.23.252.214, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_111.23.252.214_04072023a7d7-72vmess"}
  - {alterId: 64, cipher: auto, network: ws, port: 58071, server: 43.155.102.33, skip-cert-verify: true, tls: true, type: vmess, uuid: 4592247e-1528-4943-8bf3-cd9bb58b31c0, ws-opts: {path: /hk6/getData},"name":"CN_43.155.102.33_04072023a7d7-122vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 25558, server: us5.netflix6.com, skip-cert-verify: true, tls: false, type: vmess, uuid: 90a9fa37-cbae-3b06-a2b8-e3879d01fc59,"name":"CN_43.153.54.84_04072023a7d7-117vmess"}
  - {network: tcp, password: cf4295378e209e70d12c5bdd017144dfd1c772d3, port: 8443, server: 3.249.129.98, skip-cert-verify: true, type: trojan,"name":"IE_3.249.129.98_04072023a7d7-298trojan"}
  - {alterId: 64, cipher: auto, network: tcp, port: 50002, server: 198.2.203.145, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"US_198.2.203.145_04072023a7d7-334vmess"}
  - {alterId: 64, cipher: auto, port: 50002, server: 112.132.215.189, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_112.132.215.189_04072023359c-1105vmess"}
  - {password: 3195b7ff-6535-4ead-aaf0-428982a39b92, port: 50328, server: kr-s-3.fuckjdieng.uk, skip-cert-verify: false, type: trojan,"name":"KR_13.124.196.41_04062023989e-375trojan"}
