# Fri May 19 16:25:49 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yml
    filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - {name: "@ Fri May 19 16:45:31 UTC 2023", type: load-balance, proxies: [E1,F1,E2,F2,E3,F3, ], url: &url "http://www.gstatic.com/generate_204", interval: &seconds 3000, strategy: &strategy round-robin}
  - {name: E0, type: select, proxies: &all [REJECT,DIRECT,TW_165.154.246.180_051920239203-655trojan,SG_138.2.81.241_051920239203-3439vmess,SG_139.59.99.243_051920239203-3031vmess,CN_112.132.215.189_05192023ffc4-43vmess,CN_36.134.16.171_051920231946-72vmess,]}
  - {name: A0, type: select, use: [ps], proxies: [A2,A3,DIRECT,A3A2,E0,A2A3 ]}
  - {name: B0, type: select, use: [ps], proxies: [A2A3,DIRECT,A3,A2,E0,A3A2 ]}
  - {name: A2A3, type: relay, proxies: [A2,A3]}
  - {name: A3A2, type: relay, proxies: [A3,A2]}
  - {name: A3, type: fallback, proxies: [A4,A1], url: &baidu "http://www.baidu.com", interval: &delay 600}
  - {name: A4, type: load-balance, proxies: [A1,F1,F2,F3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A2, type: load-balance, proxies: [E1,E2,E3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A1, type: load-balance, use: [ps], url: *url, interval: *seconds, strategy: *strategy} 
  - {name: E1, type: url-test, proxies: [CN_112.132.215.189_05192023ffc4-43vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F1, type: load-balance, proxies: [TW_165.154.246.180_051920239203-655trojan,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E2, type: url-test, proxies: [CN_36.134.16.171_051920231946-72vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F2, type: load-balance, proxies: [SG_138.2.81.241_051920239203-3439vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E3, type: url-test, proxies: [REJECT], url: *baidu, interval: *seconds}    
  - {name: F3, type: load-balance, proxies: [SG_139.59.99.243_051920239203-3031vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
proxies:
  - {alterId: 64, cipher: auto, port: 50002, server: 112.132.215.189, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_112.132.215.189_05192023ffc4-43vmess"}
  - {alterId: 0, cipher: auto, network: tcp, port: 11023, server: 36.134.16.171, skip-cert-verify: true, type: vmess, uuid: 8c042a38-71c1-1dcb-00df-54880236e0dc,"name":"CN_36.134.16.171_051920231946-72vmess"}
  - {password: ca7febc2-bb45-4e6d-810e-ab0af6009c4e, port: 443, server: 165.154.246.180, skip-cert-verify: true, type: trojan,"name":"TW_165.154.246.180_051920239203-655trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: 139.59.99.243, skip-cert-verify: false, tls: false, type: vmess, uuid: 1d1c1d94-6987-4658-a4dc-8821a30fe7e0, ws-opts: {path: /vmess},"name":"SG_139.59.99.243_051920239203-3031vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: sg1.clare88.cf, skip-cert-verify: false, tls: true, type: vmess, uuid: 85b5582a-76e5-436d-d725-cd617e4155e4, ws-opts: {path: /shen},"name":"SG_138.2.81.241_051920239203-3439vmess"}
