# Thu Apr 13 08:15:57 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yml
    filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - {name: "@ Thu Apr 13 08:35:49 UTC 2023", type: load-balance, proxies: [E1,F1,E2,F2,E3,F3, ], url: &url "http://www.gstatic.com/generate_204", interval: &seconds 3000, strategy: &strategy round-robin}
  - {name: E0, type: select, proxies: &all [REJECT,DIRECT,IN_152.67.160.174_04132023ec9d-238trojan,JP_152.69.197.74_04132023ec9d-331vmess,US_161.129.34.102_04132023ec9d-354vmess,US_142.4.126.55_04132023ec9d-336vmess,DE_78.47.92.139_04132023ec9d-471trojan,GB_185.16.206.212_04132023ec9d-482trojan,GB_51.89.105.176_04132023ec9d-230vmess,CN_116.192.170.16_04132023ec9d-99trojan,CN_43.154.34.49_04132023ec9d-53vmess,CN_59.36.139.14_04132023ec9d-115vmess,CN_118.212.143.20_04132023ec9d-117trojan,CN_111.23.252.215_04132023255e-1141vmess,CN_103.56.60.109_04132023255e-1134vmess,CN_111.23.252.214_04122023b5cb-43vmess,]}
  - {name: A0, type: select, use: [ps], proxies: [A2,A3,DIRECT,A3A2,E0,A2A3 ]}
  - {name: B0, type: select, use: [ps], proxies: [A2A3,DIRECT,A3,A2,E0,A3A2 ]}
  - {name: A2A3, type: relay, proxies: [A2,A3]}
  - {name: A3A2, type: relay, proxies: [A3,A2]}
  - {name: A3, type: fallback, proxies: [A4,A1], url: &baidu "http://www.baidu.com", interval: &delay 600}
  - {name: A4, type: load-balance, proxies: [A1,F1,F2,F3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A2, type: load-balance, proxies: [E1,E2,E3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A1, type: load-balance, use: [ps], url: *url, interval: *seconds, strategy: *strategy} 
  - {name: E1, type: url-test, proxies: [CN_116.192.170.16_04132023ec9d-99trojan,CN_118.212.143.20_04132023ec9d-117trojan,CN_111.23.252.214_04122023b5cb-43vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F1, type: load-balance, proxies: [IN_152.67.160.174_04132023ec9d-238trojan,US_142.4.126.55_04132023ec9d-336vmess,GB_51.89.105.176_04132023ec9d-230vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E2, type: url-test, proxies: [CN_43.154.34.49_04132023ec9d-53vmess,CN_111.23.252.215_04132023255e-1141vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F2, type: load-balance, proxies: [JP_152.69.197.74_04132023ec9d-331vmess,DE_78.47.92.139_04132023ec9d-471trojan,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E3, type: url-test, proxies: [CN_59.36.139.14_04132023ec9d-115vmess,CN_103.56.60.109_04132023255e-1134vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F3, type: load-balance, proxies: [US_161.129.34.102_04132023ec9d-354vmess,GB_185.16.206.212_04132023ec9d-482trojan,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
proxies:
  - {alterId: 64, cipher: auto, port: 45070, server: 111.23.252.214, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_111.23.252.214_04122023b5cb-43vmess"}
  - {alterId: 64, cipher: auto, network: tcp, port: 58812, server: 51.89.105.176, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"GB_51.89.105.176_04132023ec9d-230vmess"}
  - {alterId: 0, cipher: auto, network: tcp, port: 23183, server: 43.154.34.49, skip-cert-verify: true, tls: false, type: vmess, uuid: b402a4af-285a-463e-c3a7-53f91efdec78,"name":"CN_43.154.34.49_04132023ec9d-53vmess"}
  - {network: tcp, password: 54080134-2cba-4535-8599-95650bd9aa54, port: 443, server: 152.67.160.174, skip-cert-verify: true, type: trojan,"name":"IN_152.67.160.174_04132023ec9d-238trojan"}
  - {alterId: 4, cipher: auto, network: ws, port: 63092, server: 59.36.139.14, tls: false, type: vmess, uuid: c796ecaf-e6ca-3eba-96d3-21df44550cbc, ws-opts: {path: /},"name":"CN_59.36.139.14_04132023ec9d-115vmess"}
  - {password: 7c0f3d97-b6ca-30f2-8e1d-60beff21f954, port: 22060, server: scloud60.jafiyun.world, skip-cert-verify: false, type: trojan,"name":"CN_118.212.143.20_04132023ec9d-117trojan"}
  - {network: tcp, password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 8443, server: official.taipeicitygovernment.com.ua, skip-cert-verify: true, type: trojan,"name":"CN_116.192.170.16_04132023ec9d-99trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 12345, server: 152.69.197.74, skip-cert-verify: false, tls: false, type: vmess, uuid: b8a6bf58-485a-4046-b386-b3661bf65eff, ws-opts: {path: /bb},"name":"JP_152.69.197.74_04132023ec9d-331vmess"}
  - {alterId: 64, cipher: auto, network: tcp, port: 33302, server: 142.4.126.55, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"US_142.4.126.55_04132023ec9d-336vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 161.129.34.102, skip-cert-verify: true, tls: true, type: vmess, uuid: ec736482-173e-3eff-9114-b49df8056e7d, ws-opts: {path: /},"name":"US_161.129.34.102_04132023ec9d-354vmess"}
  - {alterId: 4, cipher: auto, network: ws, port: 30007, server: hncu.xdyxuj.xyz, tls: false, type: vmess, uuid: 01885776-6232-3ac4-bbd3-daa77b23c18a, ws-opts: {path: /},"name":"CN_103.56.60.109_04132023255e-1134vmess"}
  - {alterId: 64, cipher: auto, port: 48767, server: 111.23.252.215, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_111.23.252.215_04132023255e-1141vmess"}
  - {network: tcp, password: shefelnak, port: 443, server: 185.16.206.212, skip-cert-verify: true, type: trojan,"name":"GB_185.16.206.212_04132023ec9d-482trojan"}
  - {network: tcp, password: xl87654321, port: 443, server: stonebreak.online, skip-cert-verify: true, type: trojan,"name":"DE_78.47.92.139_04132023ec9d-471trojan"}
