# Tue May  9 16:25:35 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yml
    filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - {name: "@ Tue May  9 16:53:46 UTC 2023", type: load-balance, proxies: [E1,F1,E2,F2,E3,F3, ], url: &url "http://www.gstatic.com/generate_204", interval: &seconds 3000, strategy: &strategy round-robin}
  - {name: E0, type: select, proxies: &all [REJECT,DIRECT,US_171.22.134.2_050920238082-727vmess,DE_130.61.111.167_050920238082-740vmess,AU_139.99.245.165_050920238082-790vmess,US_38.40.219.180_050920238082-815vmess,IR_185.143.233.122_050820238eea-555vmess,GOOGLE_35.225.69.73_050920238082-784vmess,CN_112.64.102.212_050820234a08-79http,CN_112.64.102.212_050820234a08-81http,CN_116.163.45.166_050920238082-757trojan,CN_43.154.34.49_050920233131-47vmess,CN_43.154.76.92_050920233131-69vmess,]}
  - {name: A0, type: select, use: [ps], proxies: [A2,A3,DIRECT,A3A2,E0,A2A3 ]}
  - {name: B0, type: select, use: [ps], proxies: [A2A3,DIRECT,A3,A2,E0,A3A2 ]}
  - {name: A2A3, type: relay, proxies: [A2,A3]}
  - {name: A3A2, type: relay, proxies: [A3,A2]}
  - {name: A3, type: fallback, proxies: [A4,A1], url: &baidu "http://www.baidu.com", interval: &delay 600}
  - {name: A4, type: load-balance, proxies: [A1,F1,F2,F3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A2, type: load-balance, proxies: [E1,E2,E3, ], url: *url, interval: *seconds, strategy: *strategy }
  - {name: A1, type: load-balance, use: [ps], url: *url, interval: *seconds, strategy: *strategy} 
  - {name: E1, type: url-test, proxies: [CN_112.64.102.212_050820234a08-79http,CN_43.154.34.49_050920233131-47vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F1, type: load-balance, proxies: [US_171.22.134.2_050920238082-727vmess,US_38.40.219.180_050920238082-815vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E2, type: url-test, proxies: [CN_112.64.102.212_050820234a08-81http,CN_43.154.76.92_050920233131-69vmess,REJECT], url: *baidu, interval: *seconds}    
  - {name: F2, type: load-balance, proxies: [DE_130.61.111.167_050920238082-740vmess,IR_185.143.233.122_050820238eea-555vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
  - {name: E3, type: url-test, proxies: [CN_116.163.45.166_050920238082-757trojan,REJECT], url: *baidu, interval: *seconds}    
  - {name: F3, type: load-balance, proxies: [AU_139.99.245.165_050920238082-790vmess,GOOGLE_35.225.69.73_050920238082-784vmess,REJECT], url: *url, interval: *seconds, strategy: *strategy}    
proxies:
  - {alterId: 0, cipher: auto, network: ws, port: 2086, server: form.tajsub.com, skip-cert-verify: true, tls: false, type: vmess, uuid: 93a3fd23-96df-49df-80e9-854fe154bbbf, ws-opts: {path: /},"name":"IR_185.143.233.122_050820238eea-555vmess"}
  - {alterId: 0, cipher: auto, port: 23183, server: 43.154.34.49, type: vmess, uuid: b402a4af-285a-463e-c3a7-53f91efdec78,"name":"CN_43.154.34.49_050920233131-47vmess"}
  - {alterId: 64, cipher: auto, network: ws, port: 25034, server: 43.154.76.92, skip-cert-verify: true, tls: true, type: vmess, uuid: 784272d2-bd2d-438a-bbd4-1271bb1f1b0d, ws-opts: {path: /hk15/getData},"name":"CN_43.154.76.92_050920233131-69vmess"}
  - {password: b91b087fa4, port: 11543, server: h295826.waihuizhibiaowang.com, skip-cert-verify: false, tls: true, type: http, username: b3b1de88b0,"name":"CN_112.64.102.212_050820234a08-81http"}
  - {password: b91b087fa4, port: 11343, server: h295826.waihuizhibiaowang.com, skip-cert-verify: false, tls: true, type: http, username: b3b1de88b0,"name":"CN_112.64.102.212_050820234a08-79http"}
  - {alterId: 64, cipher: auto, port: 53433, server: 171.22.134.2, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"US_171.22.134.2_050920238082-727vmess"}
  - {alterId: 0, cipher: auto, network: tcp, port: 21872, server: 130.61.111.167, skip-cert-verify: true, tls: false, type: vmess, uuid: 9a7a75d4-ab7e-4ba0-bbfa-a4acddc18084,"name":"DE_130.61.111.167_050920238082-740vmess"}
  - {password: 373dcbfc-9b35-3515-b9e0-11aac8757d3f, port: 22043, server: scloud43.jafiyun.world, skip-cert-verify: false, type: trojan,"name":"CN_116.163.45.166_050920238082-757trojan"}
  - {alterId: 64, cipher: auto, port: 50002, server: 139.99.245.165, skip-cert-verify: false, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"AU_139.99.245.165_050920238082-790vmess"}
  - {alterId: 64, cipher: auto, port: 53362, server: 38.40.219.180, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"US_38.40.219.180_050920238082-815vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: sv1-pikachujp.cloud.okteto.net, skip-cert-verify: false, tls: true, type: vmess, uuid: 6fc5e917-5a12-4a94-9d73-800c6cad025d, ws-opts: {path: /vmess},"name":"GOOGLE_35.225.69.73_050920238082-784vmess"}
